---

# This task migrates and seeds the database created

- name: Populate the database
  command:
    cmd: php artisan migrate --seed
    chdir: '{{ project_path }}'
  notify: Restart mysql
  register: seed
  changed_when: seed.stderr != ""
  ignore_errors: yes
  tags: migrate
